spring:
  jmx: 
    enabled: true
  application:
    name: spring-docker-poc
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  codec:
    max-in-memory-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probablity: 1.0     
  prometheus:
    metrics:
      export:
        enabled: true

azure:
  storage:
    container:
      name: webappcontainer
    connection:
      string: DefaultEndpointsProtocol=https;AccountName=webapplayergenricstroage;AccountKey=duBCtud/fl3O5qsuQg81KlZqG7TtByreozV+EDcRx5PL3QSdVaxlyVmf2ggZrxJaaG/MnHUYLNjd+ASt+Be2Nw==;EndpointSuffix=core.windows.net       


jasypt:
  encryptor:
    algorithm: PBEWITHSHA256AND256BITAES-CBC-BC
    provider-class-name: org.bouncycastle.jce.provider.BouncyCastleProvider
    password: IamBatman@07

swagger:
  openapi:
    local-url: http://localhost:8080
    local-desc: Local Environment 
    dev-url: http://localhost:8080
    dev-desc: Dev Environment
    test-url: http://localhost:8080
    test-desc: Test Environment
    stage-url: http://localhost:8080
    stage-desc: Stage Environment
    prod-url: https://prod-api.com
    prod-desc: Prod Environment
    contact-email: sachin19927@gmail.com
    contact-name: SACHIN H S
    contact-url: 
    license-name: RIT License
    license-url: https://choosealicense.com/licenses/mit/
    info-title: Web App Backend API
    info-version: 1.0
    info-desc: This API exposes endpoints to manage Common Web Apps
    info-term-service: https://github.com/sachin19927