spring:
  application:
    name: spring-docker-poc
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://3.109.189.129:9411/api/v2/spans
  tracing:
    sampling:
      probablity: 1.0     
       