name: Deploy to Aws
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select The environment
        default: dev
        required: true
      release-build:
        type: boolean
        description: Wheather is this a release build?
        default: false
concurrency:
  group: ${{github.workflow}}-${{github.ref}}-${{github.event.environment || 'dev'}}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: self-hosted
    environment: ${{github.event.environment || 'dev'}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn clean install

    - name: Run the application
      run: mvn spring-boot:run
