name: Deploy to Aws Backend Services
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select The environment
        default: dev
        required: true
      release-build:
        type: boolean
        description: Wheather is this a release build?
        default: false
concurrency:
  group: ${{github.workflow}}-${{github.ref}}-${{github.event.environment || 'dev'}}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: self-hosted-aws-backend
    env:
      RUN_ID: ${{github.run_id}}
      APP_NAME: spring-docker-poc
      REGISTRY: 773120352783.dkr.ecr.ap-south-1.amazonaws.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build with Maven
      run: mvn clean install
