name: Deploy to Aws
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select The environment
        default: dev
        required: true
      release-build:
        type: boolean
        description: Wheather is this a release build?
        default: false
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin' # Or another distribution like 'zulu' or 'adopt'

    - name: Display Java version
      run: java -version

    - name: Display Maven version
      run: mvn -version  

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run the application
      run: mvn spring-boot:run
